name: Build and Release

on:
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Version
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version
      - name: Build artifacts
        run: make build
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          draft: false
          files: |
            ./dist/darwin_amd64.tar.gz
            ./dist/darwin_arm64.tar.gz
            ./dist/linux_amd64.tar.gz
            ./dist/windows_amd64.zip
          generate_release_notes: true
          name: ${{ steps.version.outputs.version }}
          prerelease: false
          tag_name: v${{ steps.version.outputs.version }}
