name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    name: Create and Push Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version
      - name: Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.version.outputs.version }} -m "${{ steps.version.outputs.version }}"
          git push origin v${{ steps.version.outputs.version }}
